#!/usr/bin/env node

/**
 * Generates TypeScript types from the backend swagger.json.
 *
 * Usage:
 *   node scripts/generate-api.mjs          — one-shot generation
 *   node scripts/generate-api.mjs --watch  — watch mode (re-generates on swagger.json change)
 */

import { execSync } from 'child_process'
import { existsSync, watchFile, statSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))

const SWAGGER_PATH = resolve(__dirname, '../../../apps/backend/swagger-output/swagger.json')
const OUTPUT_PATH = resolve(__dirname, '../src/app/lib/api/v1.d.ts')

function generate() {
  if (!existsSync(SWAGGER_PATH)) {
    console.log('⏳ Waiting for swagger.json to be generated by the backend...')
    return false
  }

  try {
    execSync(`npx openapi-typescript ${SWAGGER_PATH} -o ${OUTPUT_PATH}`, {
      stdio: 'inherit',
      cwd: resolve(__dirname, '..'),
    })
    console.log('✅ API types generated at src/app/lib/api/v1.d.ts')
    return true
  } catch (error) {
    console.error('❌ Failed to generate API types:', error.message)
    return false
  }
}

const isWatch = process.argv.includes('--watch')

// Initial generation
generate()

if (isWatch) {
  console.log('👀 Watching for swagger.json changes...')

  let lastSize = 0
  try {
    lastSize = statSync(SWAGGER_PATH).size
  } catch {
    // file doesn't exist yet
  }

  watchFile(SWAGGER_PATH, { interval: 1000 }, (curr) => {
    if (curr.size > 0 && curr.size !== lastSize) {
      lastSize = curr.size
      console.log('\n🔄 swagger.json changed, regenerating types...')
      generate()
    }
  })
}
