/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganisationsRouteImport } from './routes/organisations'
import { Route as InvitationRouteImport } from './routes/invitation'
import { Route as CreateOrganisationRouteImport } from './routes/create-organisation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalMentionsRouteImport } from './routes/legal/mentions'
import { Route as LegalConditionsRouteImport } from './routes/legal/conditions'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppOrgSlugRouteRouteImport } from './routes/app/$orgSlug/route'
import { Route as LegalFrPrivacyRouteImport } from './routes/legal/fr/privacy'
import { Route as LegalFrConditionsRouteImport } from './routes/legal/fr/conditions'
import { Route as LegalEnPrivacyRouteImport } from './routes/legal/en/privacy'
import { Route as LegalEnConditionsRouteImport } from './routes/legal/en/conditions'
import { Route as AppOrgSlugWebsiteRouteImport } from './routes/app/$orgSlug/website'
import { Route as AppOrgSlugTicketsRouteImport } from './routes/app/$orgSlug/tickets'
import { Route as AppOrgSlugStatsRouteImport } from './routes/app/$orgSlug/stats'
import { Route as AppOrgSlugSettingsRouteImport } from './routes/app/$orgSlug/settings'
import { Route as AppOrgSlugPromotionsRouteImport } from './routes/app/$orgSlug/promotions'
import { Route as AppOrgSlugPlanRouteImport } from './routes/app/$orgSlug/plan'
import { Route as AppOrgSlugNotificationsRouteImport } from './routes/app/$orgSlug/notifications'
import { Route as AppOrgSlugMembersRouteImport } from './routes/app/$orgSlug/members'
import { Route as AppOrgSlugLegalRouteImport } from './routes/app/$orgSlug/legal'
import { Route as AppOrgSlugDashboardRouteImport } from './routes/app/$orgSlug/dashboard'
import { Route as AppOrgSlugCatalogRouteImport } from './routes/app/$orgSlug/catalog'
import { Route as AppOrgSlugAgentRouteImport } from './routes/app/$orgSlug/agent'
import { Route as AppOrgSlugCommentsIdRouteImport } from './routes/app/$orgSlug/comments/$id'
import { Route as AppOrgSlugChatsIdRouteImport } from './routes/app/$orgSlug/chats/$id'

const OrganisationsRoute = OrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationRoute = InvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrganisationRoute = CreateOrganisationRouteImport.update({
  id: '/create-organisation',
  path: '/create-organisation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalMentionsRoute = LegalMentionsRouteImport.update({
  id: '/legal/mentions',
  path: '/legal/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalConditionsRoute = LegalConditionsRouteImport.update({
  id: '/legal/conditions',
  path: '/legal/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgSlugRouteRoute = AppOrgSlugRouteRouteImport.update({
  id: '/app/$orgSlug',
  path: '/app/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalFrPrivacyRoute = LegalFrPrivacyRouteImport.update({
  id: '/legal/fr/privacy',
  path: '/legal/fr/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalFrConditionsRoute = LegalFrConditionsRouteImport.update({
  id: '/legal/fr/conditions',
  path: '/legal/fr/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalEnPrivacyRoute = LegalEnPrivacyRouteImport.update({
  id: '/legal/en/privacy',
  path: '/legal/en/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalEnConditionsRoute = LegalEnConditionsRouteImport.update({
  id: '/legal/en/conditions',
  path: '/legal/en/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgSlugWebsiteRoute = AppOrgSlugWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugTicketsRoute = AppOrgSlugTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugStatsRoute = AppOrgSlugStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugSettingsRoute = AppOrgSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugPromotionsRoute = AppOrgSlugPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugPlanRoute = AppOrgSlugPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugNotificationsRoute = AppOrgSlugNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugMembersRoute = AppOrgSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugLegalRoute = AppOrgSlugLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugDashboardRoute = AppOrgSlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugCatalogRoute = AppOrgSlugCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugAgentRoute = AppOrgSlugAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugCommentsIdRoute = AppOrgSlugCommentsIdRouteImport.update({
  id: '/comments/$id',
  path: '/comments/$id',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)
const AppOrgSlugChatsIdRoute = AppOrgSlugChatsIdRouteImport.update({
  id: '/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => AppOrgSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-organisation': typeof CreateOrganisationRoute
  '/invitation': typeof InvitationRoute
  '/organisations': typeof OrganisationsRoute
  '/app/$orgSlug': typeof AppOrgSlugRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/conditions': typeof LegalConditionsRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/blog/': typeof BlogIndexRoute
  '/app/$orgSlug/agent': typeof AppOrgSlugAgentRoute
  '/app/$orgSlug/catalog': typeof AppOrgSlugCatalogRoute
  '/app/$orgSlug/dashboard': typeof AppOrgSlugDashboardRoute
  '/app/$orgSlug/legal': typeof AppOrgSlugLegalRoute
  '/app/$orgSlug/members': typeof AppOrgSlugMembersRoute
  '/app/$orgSlug/notifications': typeof AppOrgSlugNotificationsRoute
  '/app/$orgSlug/plan': typeof AppOrgSlugPlanRoute
  '/app/$orgSlug/promotions': typeof AppOrgSlugPromotionsRoute
  '/app/$orgSlug/settings': typeof AppOrgSlugSettingsRoute
  '/app/$orgSlug/stats': typeof AppOrgSlugStatsRoute
  '/app/$orgSlug/tickets': typeof AppOrgSlugTicketsRoute
  '/app/$orgSlug/website': typeof AppOrgSlugWebsiteRoute
  '/legal/en/conditions': typeof LegalEnConditionsRoute
  '/legal/en/privacy': typeof LegalEnPrivacyRoute
  '/legal/fr/conditions': typeof LegalFrConditionsRoute
  '/legal/fr/privacy': typeof LegalFrPrivacyRoute
  '/app/$orgSlug/chats/$id': typeof AppOrgSlugChatsIdRoute
  '/app/$orgSlug/comments/$id': typeof AppOrgSlugCommentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-organisation': typeof CreateOrganisationRoute
  '/invitation': typeof InvitationRoute
  '/organisations': typeof OrganisationsRoute
  '/app/$orgSlug': typeof AppOrgSlugRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/conditions': typeof LegalConditionsRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/blog': typeof BlogIndexRoute
  '/app/$orgSlug/agent': typeof AppOrgSlugAgentRoute
  '/app/$orgSlug/catalog': typeof AppOrgSlugCatalogRoute
  '/app/$orgSlug/dashboard': typeof AppOrgSlugDashboardRoute
  '/app/$orgSlug/legal': typeof AppOrgSlugLegalRoute
  '/app/$orgSlug/members': typeof AppOrgSlugMembersRoute
  '/app/$orgSlug/notifications': typeof AppOrgSlugNotificationsRoute
  '/app/$orgSlug/plan': typeof AppOrgSlugPlanRoute
  '/app/$orgSlug/promotions': typeof AppOrgSlugPromotionsRoute
  '/app/$orgSlug/settings': typeof AppOrgSlugSettingsRoute
  '/app/$orgSlug/stats': typeof AppOrgSlugStatsRoute
  '/app/$orgSlug/tickets': typeof AppOrgSlugTicketsRoute
  '/app/$orgSlug/website': typeof AppOrgSlugWebsiteRoute
  '/legal/en/conditions': typeof LegalEnConditionsRoute
  '/legal/en/privacy': typeof LegalEnPrivacyRoute
  '/legal/fr/conditions': typeof LegalFrConditionsRoute
  '/legal/fr/privacy': typeof LegalFrPrivacyRoute
  '/app/$orgSlug/chats/$id': typeof AppOrgSlugChatsIdRoute
  '/app/$orgSlug/comments/$id': typeof AppOrgSlugCommentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-organisation': typeof CreateOrganisationRoute
  '/invitation': typeof InvitationRoute
  '/organisations': typeof OrganisationsRoute
  '/app/$orgSlug': typeof AppOrgSlugRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/conditions': typeof LegalConditionsRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/blog/': typeof BlogIndexRoute
  '/app/$orgSlug/agent': typeof AppOrgSlugAgentRoute
  '/app/$orgSlug/catalog': typeof AppOrgSlugCatalogRoute
  '/app/$orgSlug/dashboard': typeof AppOrgSlugDashboardRoute
  '/app/$orgSlug/legal': typeof AppOrgSlugLegalRoute
  '/app/$orgSlug/members': typeof AppOrgSlugMembersRoute
  '/app/$orgSlug/notifications': typeof AppOrgSlugNotificationsRoute
  '/app/$orgSlug/plan': typeof AppOrgSlugPlanRoute
  '/app/$orgSlug/promotions': typeof AppOrgSlugPromotionsRoute
  '/app/$orgSlug/settings': typeof AppOrgSlugSettingsRoute
  '/app/$orgSlug/stats': typeof AppOrgSlugStatsRoute
  '/app/$orgSlug/tickets': typeof AppOrgSlugTicketsRoute
  '/app/$orgSlug/website': typeof AppOrgSlugWebsiteRoute
  '/legal/en/conditions': typeof LegalEnConditionsRoute
  '/legal/en/privacy': typeof LegalEnPrivacyRoute
  '/legal/fr/conditions': typeof LegalFrConditionsRoute
  '/legal/fr/privacy': typeof LegalFrPrivacyRoute
  '/app/$orgSlug/chats/$id': typeof AppOrgSlugChatsIdRoute
  '/app/$orgSlug/comments/$id': typeof AppOrgSlugCommentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-organisation'
    | '/invitation'
    | '/organisations'
    | '/app/$orgSlug'
    | '/auth/callback'
    | '/auth/login'
    | '/blog/$slug'
    | '/legal/conditions'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/blog/'
    | '/app/$orgSlug/agent'
    | '/app/$orgSlug/catalog'
    | '/app/$orgSlug/dashboard'
    | '/app/$orgSlug/legal'
    | '/app/$orgSlug/members'
    | '/app/$orgSlug/notifications'
    | '/app/$orgSlug/plan'
    | '/app/$orgSlug/promotions'
    | '/app/$orgSlug/settings'
    | '/app/$orgSlug/stats'
    | '/app/$orgSlug/tickets'
    | '/app/$orgSlug/website'
    | '/legal/en/conditions'
    | '/legal/en/privacy'
    | '/legal/fr/conditions'
    | '/legal/fr/privacy'
    | '/app/$orgSlug/chats/$id'
    | '/app/$orgSlug/comments/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-organisation'
    | '/invitation'
    | '/organisations'
    | '/app/$orgSlug'
    | '/auth/callback'
    | '/auth/login'
    | '/blog/$slug'
    | '/legal/conditions'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/blog'
    | '/app/$orgSlug/agent'
    | '/app/$orgSlug/catalog'
    | '/app/$orgSlug/dashboard'
    | '/app/$orgSlug/legal'
    | '/app/$orgSlug/members'
    | '/app/$orgSlug/notifications'
    | '/app/$orgSlug/plan'
    | '/app/$orgSlug/promotions'
    | '/app/$orgSlug/settings'
    | '/app/$orgSlug/stats'
    | '/app/$orgSlug/tickets'
    | '/app/$orgSlug/website'
    | '/legal/en/conditions'
    | '/legal/en/privacy'
    | '/legal/fr/conditions'
    | '/legal/fr/privacy'
    | '/app/$orgSlug/chats/$id'
    | '/app/$orgSlug/comments/$id'
  id:
    | '__root__'
    | '/'
    | '/create-organisation'
    | '/invitation'
    | '/organisations'
    | '/app/$orgSlug'
    | '/auth/callback'
    | '/auth/login'
    | '/blog/$slug'
    | '/legal/conditions'
    | '/legal/mentions'
    | '/legal/privacy'
    | '/blog/'
    | '/app/$orgSlug/agent'
    | '/app/$orgSlug/catalog'
    | '/app/$orgSlug/dashboard'
    | '/app/$orgSlug/legal'
    | '/app/$orgSlug/members'
    | '/app/$orgSlug/notifications'
    | '/app/$orgSlug/plan'
    | '/app/$orgSlug/promotions'
    | '/app/$orgSlug/settings'
    | '/app/$orgSlug/stats'
    | '/app/$orgSlug/tickets'
    | '/app/$orgSlug/website'
    | '/legal/en/conditions'
    | '/legal/en/privacy'
    | '/legal/fr/conditions'
    | '/legal/fr/privacy'
    | '/app/$orgSlug/chats/$id'
    | '/app/$orgSlug/comments/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateOrganisationRoute: typeof CreateOrganisationRoute
  InvitationRoute: typeof InvitationRoute
  OrganisationsRoute: typeof OrganisationsRoute
  AppOrgSlugRouteRoute: typeof AppOrgSlugRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LegalConditionsRoute: typeof LegalConditionsRoute
  LegalMentionsRoute: typeof LegalMentionsRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LegalEnConditionsRoute: typeof LegalEnConditionsRoute
  LegalEnPrivacyRoute: typeof LegalEnPrivacyRoute
  LegalFrConditionsRoute: typeof LegalFrConditionsRoute
  LegalFrPrivacyRoute: typeof LegalFrPrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organisations': {
      id: '/organisations'
      path: '/organisations'
      fullPath: '/organisations'
      preLoaderRoute: typeof OrganisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation': {
      id: '/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof InvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-organisation': {
      id: '/create-organisation'
      path: '/create-organisation'
      fullPath: '/create-organisation'
      preLoaderRoute: typeof CreateOrganisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/mentions': {
      id: '/legal/mentions'
      path: '/legal/mentions'
      fullPath: '/legal/mentions'
      preLoaderRoute: typeof LegalMentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/conditions': {
      id: '/legal/conditions'
      path: '/legal/conditions'
      fullPath: '/legal/conditions'
      preLoaderRoute: typeof LegalConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$orgSlug': {
      id: '/app/$orgSlug'
      path: '/app/$orgSlug'
      fullPath: '/app/$orgSlug'
      preLoaderRoute: typeof AppOrgSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/fr/privacy': {
      id: '/legal/fr/privacy'
      path: '/legal/fr/privacy'
      fullPath: '/legal/fr/privacy'
      preLoaderRoute: typeof LegalFrPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/fr/conditions': {
      id: '/legal/fr/conditions'
      path: '/legal/fr/conditions'
      fullPath: '/legal/fr/conditions'
      preLoaderRoute: typeof LegalFrConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/en/privacy': {
      id: '/legal/en/privacy'
      path: '/legal/en/privacy'
      fullPath: '/legal/en/privacy'
      preLoaderRoute: typeof LegalEnPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/en/conditions': {
      id: '/legal/en/conditions'
      path: '/legal/en/conditions'
      fullPath: '/legal/en/conditions'
      preLoaderRoute: typeof LegalEnConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$orgSlug/website': {
      id: '/app/$orgSlug/website'
      path: '/website'
      fullPath: '/app/$orgSlug/website'
      preLoaderRoute: typeof AppOrgSlugWebsiteRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/tickets': {
      id: '/app/$orgSlug/tickets'
      path: '/tickets'
      fullPath: '/app/$orgSlug/tickets'
      preLoaderRoute: typeof AppOrgSlugTicketsRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/stats': {
      id: '/app/$orgSlug/stats'
      path: '/stats'
      fullPath: '/app/$orgSlug/stats'
      preLoaderRoute: typeof AppOrgSlugStatsRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/settings': {
      id: '/app/$orgSlug/settings'
      path: '/settings'
      fullPath: '/app/$orgSlug/settings'
      preLoaderRoute: typeof AppOrgSlugSettingsRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/promotions': {
      id: '/app/$orgSlug/promotions'
      path: '/promotions'
      fullPath: '/app/$orgSlug/promotions'
      preLoaderRoute: typeof AppOrgSlugPromotionsRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/plan': {
      id: '/app/$orgSlug/plan'
      path: '/plan'
      fullPath: '/app/$orgSlug/plan'
      preLoaderRoute: typeof AppOrgSlugPlanRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/notifications': {
      id: '/app/$orgSlug/notifications'
      path: '/notifications'
      fullPath: '/app/$orgSlug/notifications'
      preLoaderRoute: typeof AppOrgSlugNotificationsRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/members': {
      id: '/app/$orgSlug/members'
      path: '/members'
      fullPath: '/app/$orgSlug/members'
      preLoaderRoute: typeof AppOrgSlugMembersRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/legal': {
      id: '/app/$orgSlug/legal'
      path: '/legal'
      fullPath: '/app/$orgSlug/legal'
      preLoaderRoute: typeof AppOrgSlugLegalRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/dashboard': {
      id: '/app/$orgSlug/dashboard'
      path: '/dashboard'
      fullPath: '/app/$orgSlug/dashboard'
      preLoaderRoute: typeof AppOrgSlugDashboardRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/catalog': {
      id: '/app/$orgSlug/catalog'
      path: '/catalog'
      fullPath: '/app/$orgSlug/catalog'
      preLoaderRoute: typeof AppOrgSlugCatalogRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/agent': {
      id: '/app/$orgSlug/agent'
      path: '/agent'
      fullPath: '/app/$orgSlug/agent'
      preLoaderRoute: typeof AppOrgSlugAgentRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/comments/$id': {
      id: '/app/$orgSlug/comments/$id'
      path: '/comments/$id'
      fullPath: '/app/$orgSlug/comments/$id'
      preLoaderRoute: typeof AppOrgSlugCommentsIdRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
    '/app/$orgSlug/chats/$id': {
      id: '/app/$orgSlug/chats/$id'
      path: '/chats/$id'
      fullPath: '/app/$orgSlug/chats/$id'
      preLoaderRoute: typeof AppOrgSlugChatsIdRouteImport
      parentRoute: typeof AppOrgSlugRouteRoute
    }
  }
}

interface AppOrgSlugRouteRouteChildren {
  AppOrgSlugAgentRoute: typeof AppOrgSlugAgentRoute
  AppOrgSlugCatalogRoute: typeof AppOrgSlugCatalogRoute
  AppOrgSlugDashboardRoute: typeof AppOrgSlugDashboardRoute
  AppOrgSlugLegalRoute: typeof AppOrgSlugLegalRoute
  AppOrgSlugMembersRoute: typeof AppOrgSlugMembersRoute
  AppOrgSlugNotificationsRoute: typeof AppOrgSlugNotificationsRoute
  AppOrgSlugPlanRoute: typeof AppOrgSlugPlanRoute
  AppOrgSlugPromotionsRoute: typeof AppOrgSlugPromotionsRoute
  AppOrgSlugSettingsRoute: typeof AppOrgSlugSettingsRoute
  AppOrgSlugStatsRoute: typeof AppOrgSlugStatsRoute
  AppOrgSlugTicketsRoute: typeof AppOrgSlugTicketsRoute
  AppOrgSlugWebsiteRoute: typeof AppOrgSlugWebsiteRoute
  AppOrgSlugChatsIdRoute: typeof AppOrgSlugChatsIdRoute
  AppOrgSlugCommentsIdRoute: typeof AppOrgSlugCommentsIdRoute
}

const AppOrgSlugRouteRouteChildren: AppOrgSlugRouteRouteChildren = {
  AppOrgSlugAgentRoute: AppOrgSlugAgentRoute,
  AppOrgSlugCatalogRoute: AppOrgSlugCatalogRoute,
  AppOrgSlugDashboardRoute: AppOrgSlugDashboardRoute,
  AppOrgSlugLegalRoute: AppOrgSlugLegalRoute,
  AppOrgSlugMembersRoute: AppOrgSlugMembersRoute,
  AppOrgSlugNotificationsRoute: AppOrgSlugNotificationsRoute,
  AppOrgSlugPlanRoute: AppOrgSlugPlanRoute,
  AppOrgSlugPromotionsRoute: AppOrgSlugPromotionsRoute,
  AppOrgSlugSettingsRoute: AppOrgSlugSettingsRoute,
  AppOrgSlugStatsRoute: AppOrgSlugStatsRoute,
  AppOrgSlugTicketsRoute: AppOrgSlugTicketsRoute,
  AppOrgSlugWebsiteRoute: AppOrgSlugWebsiteRoute,
  AppOrgSlugChatsIdRoute: AppOrgSlugChatsIdRoute,
  AppOrgSlugCommentsIdRoute: AppOrgSlugCommentsIdRoute,
}

const AppOrgSlugRouteRouteWithChildren = AppOrgSlugRouteRoute._addFileChildren(
  AppOrgSlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateOrganisationRoute: CreateOrganisationRoute,
  InvitationRoute: InvitationRoute,
  OrganisationsRoute: OrganisationsRoute,
  AppOrgSlugRouteRoute: AppOrgSlugRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  LegalConditionsRoute: LegalConditionsRoute,
  LegalMentionsRoute: LegalMentionsRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  BlogIndexRoute: BlogIndexRoute,
  LegalEnConditionsRoute: LegalEnConditionsRoute,
  LegalEnPrivacyRoute: LegalEnPrivacyRoute,
  LegalFrConditionsRoute: LegalFrConditionsRoute,
  LegalFrPrivacyRoute: LegalFrPrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
